version: '3'
services:
  mongo:
    image: 'mongo'
    environment:
      MONGO_INITDB_DATABASE: <your_dataBase_name>
    expose:
      - 27017
  redis:
    image: 'redis:alpine'
    expose:
      - 6379
  distanceapp:
    restart: always
    build: .
    volumes:
      - distanceapp:/usr/src/app/debug.log
    ports:
      - "5000:5000"
    links:
      - redis
      - mongo
volumes:
  distanceapp:% 
  
